FROM python:3.11-slim

WORKDIR /app

COPY ./frontend/requirements.txt $PROJECT_ROOT
RUN python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ $PROJECT_ROOT

EXPOSE 8777

CMD ["streamlit", "run", "app.py", "--server.port=8777", "--server.address=0.0.0.0"]