FROM pytorch/pytorch:2.9.1-cuda13.0-cudnn9-runtime AS base
ARG CONTEXT='runtime'
WORKDIR /app

ENV HF_HUB_ENABLE_HF_TRANSFER=0
ENV HF_HUB_DISABLE_TELEMETRY=1
ENV HF_HUB_OFFLINE=0

COPY ./backend/requirements.txt $PROJECT_ROOT

RUN python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ $PROJECT_ROOT


CMD ["python", "-m", "app.main"]