# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-12-02T17:49:09+00:00

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from typing import Union

from fastapi import BackgroundTasks, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from lib.config import ModelConfig, TrainConfig
from lib.database import AsyncSessionLocal, DataSample, export_data
from lib.model_onnx import GeoAkinatorModelOnnx
from lib.utils import get_free_port, start_tensorboard
from train.train import get_exp_name, train_model

from .models import (
    AddDataRequest,
    AddDataResponse,
    ErrorResponse,
    MetadataResponse,
    MetricsResponse,
    PredictionRequest,
    PredictionResponse,
    RetrainRequest,
    RetrainResponse,
    Status,
)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)
model_config = ModelConfig(
    model_path="data/model/model_v1.onnx",
    tokenizer_path="data/tokenizers/tokenizer_v1",
)
train_config = TrainConfig(
    csv_save_path="data/actual_ds.csv",
    output_path="train/data",
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting GeoAkinator Service...")
    app.state.tensorboard_processes = {}
    try:
        logger.info(
            f"Try to load GeoAkinator model with path: {model_config.model_path}"
        )
    except Exception:
        raise HTTPException(status_code=500, detail="Can't find model config")

    try:
        app.state.model = GeoAkinatorModelOnnx(
            model_config.model_path, model_config.tokenizer_path
        )
    except Exception:
        raise HTTPException(status_code=500, detail="Can't init ML model")

    logger.info("Model is ready")
    yield

    logger.info("Shutting down GeoAkinator Service...")
    app.state.model = None
    app.state.tensorboard_processes = None


app = FastAPI(
    title="GeoAkinator Service API",
    description="ML service for GeoAkinator model inference\n",
    version="1.0.0",
    servers=[
        {"url": "http://0.0.0.0:8060"},
        {"url": "https://geoakinator.swagger.io/v1"},
    ],
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post(
    "/forward",
    response_model=PredictionResponse,
    responses={
        "400": {"model": ErrorResponse},
        "403": {"model": ErrorResponse},
        "500": {"model": ErrorResponse},
    },
    tags=["GeoAkinator"],
)
def forward_model(body: PredictionRequest) -> Union[PredictionResponse, ErrorResponse]:
    """
    Forward ML model to get coordinates
    """
    try:
        logger.info(f"Processing request for text: {body.text[:100]}...")
        lat, lon = app.state.model.predict(body.text)
        predictions = {"lat": lat, "lon": lon}

        logger.info(f"Prediction: lat={lat}, lon={lon}")

        return PredictionResponse(status=Status.success, predictions=predictions)

    except ValueError as e:
        logger.error(f"Model failed: {str(e)}")
        raise HTTPException(status_code=403, detail="Model couldn't process the data")
    except Exception as e:
        logger.error(f"Unexpected error in forward_model: {str(e)}")
        raise HTTPException(status_code=500, detail="Server error")


@app.get(
    "/metadata",
    response_model=MetadataResponse,
    responses={"500": {"model": ErrorResponse}},
    tags=["GeoAkinator"],
)
def get_metadata() -> Union[MetadataResponse, ErrorResponse]:
    """
    Get model metadata
    """
    try:
        logger.info("Processing to get metadata from model")
        metadata = app.state.model.get_metadata()
        logger.info(f"Metadata load success: {metadata}")
        if all(
            [
                prop in metadata.keys()
                for prop in ("commit_hash", "model_save_date", "experiment_name")
            ]
        ):
            return MetadataResponse(status=Status.success, metadata=metadata)
        else:
            raise ValueError(f"bad metadata: {metadata}")
    except ValueError as e:
        logger.error(f"Not needable key in metadata: {str(e)}")
        raise HTTPException(status_code=500, detail="Not needable data in metadata")
    except Exception as e:
        logger.error(f"Unexpected error in getting metadata: {str(e)}")
        raise HTTPException(status_code=500, detail="Server error")


@app.put(
    "/add_data",
    response_model=AddDataResponse,
    responses={"500": {"model": ErrorResponse}},
    tags=["GeoAkinator"],
)
async def add_data(body: AddDataRequest) -> Union[AddDataResponse, ErrorResponse]:
    """
    Add data to db
    """
    try:
        logger.info(
            f"Processing request for coords {body.coords.lat, body.coords.lon}"
            "by: {body.text[:100]}..."
        )
        async with AsyncSessionLocal() as session:
            new_sample = DataSample(
                text=body.text, lat=body.coords.lat, lon=body.coords.lon
            )
            session.add(new_sample)
            await session.commit()
        logger.info("Data added")

        return AddDataResponse(
            status=Status.success,
        )

    except Exception as e:
        logger.error(f"Unexpected error in add data: {str(e)}")
        raise HTTPException(status_code=500, detail="Server error")


@app.put(
    "/retrain",
    response_model=RetrainResponse,
    responses={"500": {"model": ErrorResponse}},
    tags=["GeoAkinator"],
)
async def retrain_model(
    body: RetrainRequest, background_tasks: BackgroundTasks
) -> Union[RetrainResponse, ErrorResponse]:
    """
    Retrain model on db data
    """
    try:
        logger.info("Processing to get actual data from db")
        await export_data(train_config.csv_save_path)
        logger.info("Data loaded. Start training...")
        exp_name = get_exp_name(train_config.output_path)
        background_tasks.add_task(
            train_model, train_config.csv_save_path, train_config.output_path, exp_name
        )
        logger.info(
            "Retraining started at background. Use /metrics/<int:experiment_id> to get tensorboard"
        )
        return RetrainResponse(
            status=Status.success, experiment_id=int(exp_name.split("model_v")[-1])
        )

    except Exception as e:
        logger.error(f"Unexpected error in retrain model: {str(e)}")
        raise HTTPException(status_code=500, detail="Server error")


@app.get(
    "/metrics/{experiment_id}",
    response_model=MetricsResponse,
    responses={"500": {"model": ErrorResponse}},
    tags=["GeoAkinator"],
)
async def get_metrics(
    experiment_id: int, background_tasks: BackgroundTasks
) -> Union[MetricsResponse, ErrorResponse]:
    """
    Get experiment metrics
    """
    try:
        logger.info(f"Processing to get metrics from experiment {experiment_id}")
        logdir = os.path.join(
            train_config.output_path, f"model_v{experiment_id}", "logs"
        )
        if not os.path.exists(logdir):
            raise ValueError(f"unknown experiment: {experiment_id}")
        if experiment_id in app.state.tensorboard_processes:
            port = app.state.tensorboard_processes[experiment_id]
        else:
            port = get_free_port()
            app.state.tensorboard_processes[experiment_id] = port
        logger.info("Port was found")
        background_tasks.add_task(start_tensorboard, logdir, port)
        url = f"http://localhost:{port}/"
        logger.info(f"Tensorboard is running on {url}")
        return MetricsResponse(
            status=Status.success,
            metrics_link=url,
        )
    except ConnectionError as e:
        logger.error(f"no free ports {str(e)}")
        raise HTTPException(status_code=500, detail="Free ports not found")
    except ValueError as e:
        logger.error(f"wrong experiment {str(e)}")
        raise HTTPException(status_code=500, detail="Experiment not found")
    except Exception as e:
        logger.error(f"Unexpected error in getting metrics: {str(e)}")
        raise HTTPException(status_code=500, detail="Server error")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.main:app", host="0.0.0.0", port=8060, reload=True, log_level="info"
    )
