# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2025-12-02T17:49:09+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class PredictionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: constr(min_length=1, max_length=10000) = Field(..., description="Input text")


class Status(Enum):
    success = "success"


class Predictions(BaseModel):
    lat: Optional[confloat(ge=-90.0, le=90.0)] = Field(
        None, description="Place latitude"
    )
    lon: confloat(ge=-180.0, le=180.0) = Field(..., description="Place longitude")


class PredictionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(..., description="Prediction status")
    predictions: Predictions = Field(..., description="Prediction")


class Metadata(BaseModel):
    commit_hash: Optional[str] = Field(None, description="Model hash")
    model_save_date: Optional[datetime] = Field(None, description="Model date saving")
    experiment_name: str = Field(..., description="Experiment name")


class MetadataResponse(BaseModel):
    status: Status = Field(..., description="Metadata status", examples=["success"])
    metadata: Metadata


class Status2(Enum):
    error = "error"


class ErrorResponse(BaseModel):
    status: Status2 = Field(..., description="Error status")
    message: str = Field(..., description="Error message")


class AddDataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: constr(min_length=1, max_length=10000) = Field(..., description="Input text")
    coords: Predictions = Field(..., description="Place coords")


class AddDataResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(..., description="Add data status")


class RetrainRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class RetrainResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status = Field(..., description="Retrain status")
    experiment_id: int = Field(..., description="Experiment id to get metrics")


class MetricsResponse(BaseModel):
    status: Status = Field(..., description="Metadata status", examples=["success"])
    metrics_link: str = Field(..., description="Link for tensorboard with metrics")


class DeployResponse(BaseModel):
    status: Status = Field(..., description="Metadata status", examples=["success"])
